### ISSUE TITLE
Response is not added to response.success.headers

### ISSUE THREAD

**Issue by jsmolar** [Kuadrant/wasm-shim#142]
No data is added to the request sent upstream when `response.success.headers` is used. The header is correctly added when I use the same spec for `AuthConfig` and standalone authorino.

AuthPolicy:
```
spec:
  rules:
    authentication:
      default:
        credentials:
          authorizationHeader:
            prefix: Bearer
        jwt:
          issuerUrl: 'http://10.0.96.144:8080/realms/realm-jsmolar--ykuo'
          ttl: 0
    response:
      success:
        headers:
          simple:
            json:
              properties:
                data:
                  selector: auth
            metrics: false
            priority: 0
```

When using the wasm-shim instead of the `ExtAuthFilter`, the upstream never sees the headers added to the request.
