### ISSUE TITLE
WASM Configuration v2

### ISSUE THREAD

**Issue by eguzki** [Kuadrant/wasm-shim#35]
### Current configuration struct

Example:
```yaml
failure_mode_deny: true
rate_limit_policies:
  - name: toystore
    rate_limit_domain: toystore-app
    upstream_cluster: rate-limit-cluster
    hostnames: ["*.toystore.com"]
    gateway_actions:
      - rules:
          - paths: ["/admin/toy"]
            methods: ["GET"]
            hosts: ["pets.toystore.com"]
        configurations:
          - actions:
            - generic_key:
                descriptor_key: admin
                descriptor_value: "1"
```

### Proposal for a new configuration struct to support [RLP v2](https://github.com/Kuadrant/kuadrant-operator/issues/156)

**Motivation** 
[RFC for the RLP v2](https://github.com/Kuadrant/architecture/blob/main/rfcs/0001-rlp-v2.md) brings `routeSelectors` and `when` conditions to qualify traffic to be rate limited. Even thought it is technically possible to implement these rules on the Limitador side using Limitador's conditions, the wasm-shim has all the available info to implement those rules for qualifying traffic at the gateway, thus saving rate limiting traffic at the Limitador side. Current wasm-shim rules based on `paths`, `methods` and `hosts` are not enough to support `routeSelectors` and `when` conditions. 

Example to illustrate the new wasm shim configuration struct

```yaml
failureMode: deny
rateLimitPolicies:
  - name: rlp-ns-A/rlp-name-A
    domain: rlp-ns-A/rlp-name-A
    service: rate-limit-cluster
    hostnames: ["*.toystore.com"]
    rules:   
      - conditions:      
        - allOf:
          - selector: <value>
            operator: <value>
            value: <value>
          - selector: <value>
            operator: <value>
            value: <value>
        - allOf:
          - selector: <value>
            operator: <value>
            value: <value>
          - selector: <value>
            operator: <value>
            value: <value>
        data:
        - selector:
            selector: <value>       # Any attribute from a well-known specification TBD ([ref](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/advanced/attributes#arch-overview-request-attributes))
            key: <value>             # Optional. If not set it defaults to `selector` field value as the descriptor key.
            default: <value>        # Optional. An optional value to use if metadata_key is empty. If not set and no value is present under the metadata_key then no descriptor is generated.
        - static:   
            key: <value>             # Required
            value: <value>          # Required
```

**Comment by eguzki** [comment]
@guicassolato open for discussion!

**Comment by guicassolato** [comment]
I still see too much of Envoy's RL protocol. Also, a mixture of snake case and camel case.

Suggestion:

```yaml
failureMode: deny # Default. Alternative (more permissive) value: 'allow'
rateLimitPolicies:
- name: toystore
  domain: toystore-app
  service: rate-limit-cluster
  hostnames: ["*.toystore.com"]
  rules: # Each `rule` object has `conditions` and `data` objects; if any block of conditions matches, the component will build a RL request payload ("descriptors") with `data`
  - conditions:      
    - allOf:
      - selector: <value>
        operator: <value>
        value: <value>
      - selector: <value>
        operator: <value>
        value: <value>
    - allOf:
      - selector: <value>
        operator: <value>
        value: <value>
      - selector: <value>
        operator: <value>
        value: <value>
    data:
    - selectors:   
        selector: <value>  # Any attribute from a well-known specification TBD ([ref](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/advanced/attributes#arch-overview-request-attributes))
        key: <value>       # Optional. If not set it defaults to `selector` field value as the descriptor key.
        default: <value>   # Optional. An optional value to use if metadata_key is empty. If not set and no value is present under the metadata_key then no descriptor is generated.
    - static:              # For RLP controller's usage only - not exposed in the RLP itself
        key: <value>       # Required
        value: <value>     # Required
```

**Comment by eguzki** [comment]
LGTM

**Comment by guicassolato** [comment]
I was thinking on a different way to structure the config now that [RLPv2](https://github.com/Kuadrant/architecture/blob/main/rfcs/0001-rlp-v2.md)'s route selectors allow to specify host names.

Today, we map `hostnames[] → RLPs`. I understand that this was a design decision thought to reflect the way the wasm-shim functions internally when it processes a request in the data plane. Indexing the configs by host name provides a straightforward path from info available in the request, to the set of rules to evaluate. It also mimics how Envoy listeners' and filter chains' configuration is organized, I reckon.

This organization, however, leads to repetition of rules whenever these apply to more than one host name. Additionally, given the current state of [kuadrant-operator#204](https://github.com/Kuadrant/kuadrant-operator/pull/204) as of https://github.com/Kuadrant/kuadrant-operator/pull/204/commits/62a4a431036f7352b739ff2e820288669bcd16ec, some incongruous rules may also be generated in the config, effectively mapping host names to rules that are known to never apply to those host names.

Although the later could be fixed by applying stricter filters on what rules (data and conditions) are mapped to each host name, I still believe we here may be **mixing how the config has to be structured with the need for an internal `hostnames[] → set of rules` index** for the wasm-shim to function.

For one who reads the wasm config, what we call `rateLimitPolicies[].name` is actually filled with a host name, despite having another field `hostnames` at the same level. This is also weird IMO.

With all that, my proposal for a re-org of the wasm config consist of:
1. `rateLimitPolicies` is a list of RLPs – not of host names;
2. RLPs do not repeat within the `rateLimitPolicies` list – I believe this may simplify reconciliation of the wasm config as well;
3. the names of the RLPs in the `rateLimitPolicies` list are filled with the actual names of the RLPs – not with host names;
4. remove the `rateLimitPolicies[].hostnames` field;
5. whatever `hostname → RLPs` index that is needed by the wasm-shim should be internal and built by the wasm-shim (well, sort of.)
    - To help with this, the config could include a separate field `pluginConfig.hostnames map[string][]string` that maps each host name to a list of corresponding names of RLPs to apply. This would be the index in fact.

E.g.:

```yaml
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: kuadrant-istio-ingressgateway
  namespace: istio-system
spec:
  phase: STATS
  pluginConfig:
    failureMode: deny
    rateLimitPolicies:
    - name: rlp-ns-1/rlp-name-1
      domain: rlp-ns-1/rlp-name-1 # redundant with `name`, but good for namespacing the rlps
      rules:
      - conditions:
        - allOf:
          - operator: startswith
            selector: request.url_path
            value: /toys
          - operator: eq
            selector: request.method
            value: GET
          - operator: eq
            selector: request.host
            value: '*.toystore.acme.com'
          - operator: neq
            selector: auth.identity.group
            value: admin
        - allOf:
          - operator: startswith
            selector: request.url_path
            value: /toys
          - operator: eq
            selector: request.method
            value: POST
          - operator: eq
            selector: request.host
            value: '*.toystore.acme.com'
          - operator: neq
            selector: auth.identity.group
            value: admin
        data:
        - static:
            key: default/toystore-per-endpoint/toys
            value: "1"
        - selector:
            selector: auth.identity.username
      - conditions:
        - allOf:
          - operator: startswith
            selector: request.url_path
            value: /assets/
          - operator: eq
            selector: request.host
            value: '*.toystore.acme.com'
        - allOf:
          - operator: startswith
            selector: request.url_path
            value: /assets/
          - operator: eq
            selector: request.host
            value: '*.toystore.io'
        data:
        - static:
            key: default/toystore-per-endpoint/assets
            value: "1"
      service: kuadrant-rate-limiting-service

    - name: rlp-ns-2/rlp-name-2
      domain: rlp-ns-2/rlp-name-2
      rules: […] # some rlp rules that also target '*.toystore.acme.com', but do not target '*.toystore.io'

    hostnames: # this is actually the index
      "*.toystore.acme.com": [rlp-ns-1/rlp-name-1, rlp-ns-2/rlp-name-2]
      "*.toystore.io": [rlp-ns-1/rlp-name-1]

  selector:
    matchLabels:
      app: istio-ingressgateway
      istio: ingressgateway
  url: oci://quay.io/kuadrant/wasm-shim:latest
```

To be fair, this design does not fix the problem of some occasional incongruous rules. For instance, take the 1st rule of the 1st RLP above when hostname == `*.toystore.io` in a request; the wasm-shim has to evaluate the entire rule to realize it won't generate any data for the RL request related to that rule, but because the 2nd rule applies and it's part of the same RLP, this RLP is nonetheless mapped to the `*.toystore.io` host name.

On the other hand, the design solves the issue of separating indexing from definition, and therefore the unnecessary repetition of rules.

Happy to hear your thoughts, @eguzki. WDYT?
