### ISSUE TITLE
Ext_authz

### ISSUE THREAD

**Issue by guicassolato** [Kuadrant/wasm-shim#58]
Make possible for the wasm-shim to issue gRPC Envoy [ext_authz](https://www.envoyproxy.io/docs/envoy/latest/api-v3/service/auth/v3/external_auth.proto#envoy-v3-api-msg-service-auth-v3-checkrequest) requests based on configuration.

Other than the main attributes `source`, `destination`, and `request` of the `CheckRequest` message, supplying values in the [`context_extensions`](https://www.envoyproxy.io/docs/envoy/latest/api-v3/service/auth/v3/attribute_context.proto#envoy-v3-api-msg-service-auth-v3-attributecontext) field must as well be supported. This will be useful to hint the [authorization service lookup](https://docs.kuadrant.io/0.8.0/authorino/docs/architecture/#host-lookup) without the constraint on the host name as the only unique identifier of effective policies (AuthConfig CRs.)

**Comment by david-martin** [comment]
@guicassolato Will this change mean that tracing behaves the same as with limitador?
That is, trace ids [do not propagate](https://github.com/envoyproxy/envoy/issues/22028) to wasm modules in Istio/Envoy, affecting trace continuity in authorino?
(in which case, we should update the tracing guide at https://docs.kuadrant.io/0.8.0/kuadrant-operator/doc/observability/tracing/ to mention this)

**Comment by guicassolato** [comment]
> @guicassolato Will this change mean that tracing behaves the same as with limitador? That is, trace ids [do not propagate](https://github.com/envoyproxy/envoy/issues/22028) to wasm modules in Istio/Envoy, affecting trace continuity in authorino? (in which case, we should update the tracing guide at https://docs.kuadrant.io/0.8.0/kuadrant-operator/doc/observability/tracing/ to mention this)

It probably does, @david-martin. Thanks for pointing this out!

**Comment by eguzki** [comment]
@didierofrivia I guess we can close this after https://github.com/Kuadrant/wasm-shim/pull/92. The RFE is

> Make possible for the wasm-shim to issue gRPC Envoy [ext_authz](https://www.envoyproxy.io/docs/envoy/latest/api-v3/service/auth/v3/external_auth.proto#envoy-v3-api-msg-service-auth-v3-checkrequest) requests based on configuration.

The wasm-shim supports that today with the configuration action
```yaml
"extensions": {
            "authorino": {
                "type": "auth",
                "endpoint": "authorino-cluster",
                "failureMode": "deny",
                "timeout": "5s"
            }
        },
...
 "actions": [
                {
                    "extension": "authorino",
                    "scope": "authconfig-A"
                }
]
```

Even though, the control plane does not use it (yet), this issue is completed IMO. wdyt? Can we close this?
